### ISSUE TITLE
SQL error when opening calendar

### ISSUE THREAD

**Issue by PfefferStift** [heimrichhannot/contao-events-bundle#2] opened 2021-04-08 12:46 UTC
Contao 4.9.13
contao-events-bundle 1.5.1
PHP 7.4

Hi!
When using **Umsetzung als Entität „tl_calendar_sub_events“** I get the following error, when trying to open a calendar:
`An exception occurred while executing 'SELECT tl_calendar_sub_events.* FROM tl_calendar_sub_events WHERE pid='1'': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'usr_p582384_1.tl_calendar_sub_events' doesn't exist`

And when using **Umsetzung durch eine Parent-Child-Beziehung** I get the following error when opening a calendar entry:
`An exception occurred while executing 'SELECT tl_calendar_events.* FROM tl_calendar_events WHERE tl_calendar_events.parentEvent = 0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_calendar_events.parentEvent' in 'where clause'`

The column "parentEvent" inside "tl_calendar_events" exists. Maybe a problem with the punctuation?

Thanks alot!

**Comment by Defcon0** [comment] 2021-04-12 09:16
Did you clear the cache and run the install tool (or the migrate command) after checking the checkbox in the settings? At least in the first case the additional table doesn't exist.

In the second case the field doesn't exist. Since it's even prefixed with the table (`tl_calendar_events.parentEvent`), it's not a punctuation issue.

@AlexejKossmann I would take that one.

**Comment by PfefferStift** [comment] 2021-04-12 11:22
That did the trick: **First** checking the checkbox, **then** clearing the cache/running the install tool.
Thank you! Quite simple, I must confess...

Follow-up question:
When using the entity **tl_calendar_sub_events** I get the following error by clicking on the sub-events icon:
`Table "tl_calendar_sub_events" is not allowed in module "calendar".`

I can solve this by adding this line to my localconfig.php
`$GLOBALS['BE_MOD']['content']['calendar']['tables'][] = 'tl_calendar_sub_events';`

But then I get stuck in the next step when I try to add a new sub event. Error:
`Argument 1 passed to tl_calendar_events::getSerpUrl() must be an instance of Contao\CalendarEventsModel, instance of HeimrichHannot\EventsBundle\Model\CalendarSubEventsModel given, called in /website/vendor/contao/core-bundle/src/Resources/contao/widgets/SerpPreview.php on line 150`

What's the general thing I am missing?
I appreciate your help very much!

**Comment by koertho** [comment] 2021-04-12 11:44
@Defcon0 The information, that the db must be updated should be at least noted in the readme.

**Comment by Defcon0** [comment] 2021-04-12 12:01
The problem is that the module overrides the calendar events model and `SerpPreview` enforces `\Contao\CalendarEventsModel`. We wrote events bundle in contao 4.4 days where Serp didn't exist I think. In the mean time we don't override the models anymore because it lead to problems many times.

Although Leo Feyer suggested to never override models, e.g. DC_Multilingual did exactly that.

So there's no general suggestion. In our case we try to avoid overriding models nowadays.

I suggest that you use the first method ("Umsetzung durch eine Parent-Child-Beziehung"). In this case the model inherits from the core model. Is that an option for you?

**Comment by PfefferStift** [comment] 2021-04-12 13:46
Thanks for the explanation!
Yes, the first method (parent-child) would also work fine for me. But here I get an Internal Server Error when trying to open a calendar:
`Argument 1 passed to HeimrichHannot\EventsBundle\Model\CalendarEventsModel::hasSubEvents() must be of the type integer, string given, called in /website/vendor/contao/core-bundle/src/Framework/Adapter.php on line 44`

Hmm.. any suggestions?

**Comment by Defcon0** [comment] 2021-04-12 13:48
Could you cast the parameter passed to hasSubEvents to int with `(int) $variable`? If it works, we can change it in the module.

BTW: I fixed the readme ;-)

**Comment by PfefferStift** [comment] 2021-04-12 15:30
You mean in vendor/heimrichhannot/contao-events-bundle/src/Model/CalendarEventsModel.php in line 20?
There we have:
`public static function hasSubEvents(int $event): bool
{
  return null !== static::getSubEvents($event);
}`

Now how do I make $event an integer?

PS: Cool, thanks! :)

**Comment by Defcon0** [comment] 2021-04-14 09:39
OK, I'll make a few changes (modernizations) and release a fix in some hours I think (I have some deadlines though, so it might be tomorrow).

**Comment by Defcon0** [comment] 2021-04-14 11:25
OK, I just released a new version. The issue should be fixed. In addition I did some refactoring for upcoming symfony versions. Could you please report if it works for you now? New version is 1.5.3.

Thanks ;-)

**Comment by PfefferStift** [comment] 2021-04-14 16:44
Wow, the **parent-child mode** works perfectly now! :)

The **tl_calendar_sub_events mode** still seems to need some adjustments by the user. I would need more hints how to set it up correctly (If you want I can post the errors) – but I'll just go with the parent-child mode.

Thanks so much!

**Closed as completed** 2021-04-21 07:14 UTC
